on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  cla:
    runs-on: ubuntu-latest
    name: Verify CLA
    steps:
      - uses: actions/checkout@v2
      - name: Checkout CLA Bot Repo
        uses: actions/checkout@v2
        with:
          repository: remix-run/cla-bot
          ref: refs/tags/0.1.0
          token: ${{ secrets.REMIX_CLA_BOT_PAT }}
          persist-credentials: false
          path: ./.github/actions/cla-bot
      - uses: ./.github/actions/cla-bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
